---
- name: Maak 1 Ceph host in elke gekozen AZ
  local_action:
    module: ec2
    vpc_subnet_id: "{{ item.value.subnet }}"
    key_name: "{{ ec2_keypair }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    wait: yes
    region: "{{ ec2_region }}"
    group: 'launch-wizard-1'
    volumes:
      - device_name: /dev/sdb
        device_type: standard
        volume_size: 8
        delete_on_termination: true
    instance_tags:
      Name: "{{ec2_tag_Name}}"
      environment: "{{ec2_tag_Environment}}"
    exact_count: "{{ item.value.count }}"
    count_tag:
      group: ceph{{ item.key }}
  register: ec2
  with_dict: "{{ ceph_nodes }}"

- debug: var=ec2
  with_items: ec2.instances

- add_host: name={{ item.public_ip }} >
            groups=tag_Type_{{ec2_tag_Type}},tag_Environment_{{ec2_tag_Environment}}
            ec2_region={{ec2_region}} 
            ec2_tag_Name={{ec2_tag_Name}}
            ec2_tag_Type={{ec2_tag_Type}}
            ec2_tag_Environment={{ec2_tag_Environment}}
            ec2_ip_address={{item.public_ip}}
  with_items: ec2.instances

- name: Wait for the instances to boot by checking the ssh port
  wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances
